Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/DateTime:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
