version: '3.0'

services:

  ethicaltree-api:
    container_name: ethicaltree-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    command: ash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 80"
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - 3001:80
    volumes:
      - .:/app
  db:
    image: mysql:5.7
    container_name: ethicaltree-mysql
    command: mysqld
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - 3308:3306
    volumes:
      - ./db-data:/var/lib/mysql

networks:
  default:
    external:
      name: ethicaltree

