version: '3.0'

services:

  ethicaltree-api:
    container_name: ethicaltree-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    command: ash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 80"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    ports:
      - 3001:80
    volumes:
      - .:/app

  sidekiq:
    container_name: ethicaltree-sidekiq
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    command: ash -c "bundle exec sidekiq"
    depends_on:
      - redis
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    container_name: ethicaltree-mysql
    command: >
      --character-set-server=utf8mb4
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - 3308:3306
    volumes:
      - ./db-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: ethicaltree-redis
    ports:
      - 6400:6379
    command: >
      --requirepass localpassword

networks:
  default:
    external:
      name: ethicaltree

