default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: ethicaltree_dev

test:
  <<: *default
  database: ethicaltree_test

production:
  <<: *default
  database: ethicaltree
  pool: 5
  host: willys-dbs.co8ijpyn0g2y.us-east-1.rds.amazonaws.com
  user: <%= ENV["AWS_DB_USERNAME"] %>
  password: <%= ENV["AWS_DB_PASSWORD"] %>
