default: &default
  adapter: mysql2
  encoding: utf8mb4
  databas: ethicaltree
  host: ethicaltree-mysql
  port: 3306
  username: root
  password: ""

development:
  <<: *default
  database: ethicaltree

test:
  <<: *default
  database: ethicaltree_test

production:
  <<: *default
  database: ethicaltree_prod
  pool: 5
  host: <%= ENV["DB_HOSTNAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
