default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  password: root

development:
  <<: *default
  database: ethicaltree_dev

test:
  <<: *default
  database: ethicaltree_test

production:
  <<: *default
  database: ethicaltree
  pool: 5
  host: localhost
  user: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: 5432
