# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  webhost: ethicaltree.local:3003
  proxyhost: cdn.ethicaltree.com
  protocol: http
  secret_key_base: c554eb6634567310bff7d49ad474f30a444d1decb4a6d8ce0f61a3f8b0f8169508622d1698cf000902dd59e2fc53d4ebe9d68c3fbca26a0ddeef81695192cc87
  fb_app_id: ''
  gmaps_api_key: AIzaSyDacdDrRM9Fo2nAcf6rNJFVe8dnyI8trTc
  ga_code: GA-FAKE-CODE
  ipstack_api_key: 2550f63ea45355c84396555a803a58ee
  aws:
    access_key: <%= ENV["AWS_API_KEY"] %>
    secret_key: <%= ENV["AWS_SECRET_KEY"] %>
    images_bucket: ethicaltree-dev
    thumbnails_bucket: ethicaltree-dev-thumbnails
    db_backups_bucket: ethicaltree-dev-db-backups
    s3_region: us-east-1
  redis:
    password: localpassword

test:
  secret_key_base: ebd9d8ecaaae05003a6cf49de378a22675fbb595f0e505860f7f543b7bd88a53a37aa739e896feaa0b680779d244da53b58d2e95f732875003018f7ba255a070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  webhost: ethicaltree.com
  proxyhost: cdn.ethicaltree.com
  protocol: https
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmaps_api_key: <%= ENV["GMAPS_API_KEY"] %>
  ga_code: <%= ENV["GA_CODE"] %>
  ipstack_api_key: <%= ENV["IPSTACK_API_KEY"] %>
  fb_app_id: '148450649196648'
  smtp:
    host: <%= ENV["AWS_SMTP_HOST"] %>
    user_name: <%= ENV["AWS_SMTP_USER_NAME"] %>
    password: <%= ENV["AWS_SMTP_PASSWORD"] %>
  aws:
    access_key: <%= ENV["AWS_API_KEY"] %>
    secret_key: <%= ENV["AWS_SECRET_KEY"] %>
    images_bucket: ethicaltree
    thumbnails_bucket: ethicaltree-thumbnails
    db_backups_bucket: ethicaltree-db-backups
    s3_region: us-east-1
  redis:
    password: <%= ENV["REDIS_PASSWORD"] %>
